"use client";
import { useAuth } from "@/components/auth/AuthProvider";
import { shopApi } from "@/lib/api/client";
import Link from "next/link";import { FormEvent,useEffect,useState } from "react";

type Order={id:number;orderNumber:string;status:string;paymentStatus:string;totalYen:number;createdAt:string};
type Address={id:number;label?:string;recipientName:string;postalCode:string;prefecture:string;city:string;addressLine1:string;addressLine2?:string;isDefault:boolean};
export default function AccountPage(){const{user,loading}=useAuth();const[orders,setOrders]=useState<Order[]>([]);const[addresses,setAddresses]=useState<Address[]>([]);const[message,setMessage]=useState("");
  const load=async()=>{const[o,a]=await Promise.all([shopApi<{orders:Order[]}>("orders"),shopApi<{addresses:Address[]}>("account/addresses")]);setOrders(o.orders);setAddresses(a.addresses);};
  useEffect(()=>{if(user)void load().catch(value=>setMessage(value instanceof Error?value.message:"Unable to load account."));},[user]);
  if(loading)return <main className="min-h-[500px] p-20 text-center">Loading…</main>;if(!user)return <main className="min-h-[500px] p-20 text-center">Please log in to open your account.</main>;
  const addAddress=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);try{await shopApi("account/addresses",{method:"POST",body:JSON.stringify(Object.fromEntries(f))});event.currentTarget.reset();setMessage("Address saved.");await load();}catch(value){setMessage(value instanceof Error?value.message:"Unable to save address.");}};
  return <main className="min-h-[650px] bg-white px-4 py-20 dark:bg-[#0b1016] dark:text-white"><div className="mx-auto max-w-frame"><h1 className="text-3xl font-bold">My account</h1><p className="mt-2 text-sm text-[#777]">{user.username} · {user.email}</p>{message&&<p className="mt-4 text-sm text-[#b40000]">{message}</p>}<div className="mt-10 grid gap-10 lg:grid-cols-2"><section><h2 className="mb-5 text-xl font-bold">Delivery addresses</h2>{addresses.map(a=><div key={a.id} className="mb-3 border p-4 text-sm dark:border-[#3a424b]"><b>{a.label||"Address"}{a.isDefault?" · Default":""}</b><p>{a.recipientName}<br/>{a.postalCode} {a.prefecture} {a.city}<br/>{a.addressLine1} {a.addressLine2}</p><button onClick={async()=>{await shopApi(`account/addresses/${a.id}`,{method:"DELETE"});await load();}} className="mt-2 text-xs underline">Remove</button></div>)}<form onSubmit={addAddress} className="grid grid-cols-2 gap-2">{[["label","Label"],["recipientName","Recipient"],["postalCode","Postal code"],["prefecture","Prefecture"],["city","City"],["addressLine1","Address line 1"],["addressLine2","Address line 2"]].map(([name,label])=><input key={name} required={!['label','addressLine2'].includes(name)} name={name} placeholder={label} className="h-10 border bg-transparent px-3 text-sm dark:border-[#444]"/>)}<label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isDefault" value="true"/>Default</label><button className="h-10 bg-[#2d3741] text-white">Add address</button></form></section><section><h2 className="mb-5 text-xl font-bold">Orders</h2>{orders.map(o=><Link href={`/account/orders/${o.orderNumber}`} key={o.id} className="mb-3 flex justify-between border p-4 text-sm dark:border-[#3a424b]"><span><b>{o.orderNumber}</b><br/>{o.status} · {o.paymentStatus}</span><b>₩ {Number(o.totalYen).toLocaleString()}</b></Link>)}{!orders.length&&<p>No orders yet.</p>}</section></div></div></main>}
